packages:
  - "apps/*"
  - "packages/*"
  - "infra/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - lucide-react@1.29.0
