import { BadRequestException, Body, Controller, Get, Injectable, Module, NotFoundException, Param, ParseUUIDPipe, Patch, Post, Query, UseGuards } from "@nestjs/common";
import { IsIn, IsNotEmpty, IsOptional, IsString, IsUUID, MaxLength } from "class-validator";
import { getPrismaClient } from "@nauterio/database";
import { AuthGuard, type AuthenticatedUser } from "../../common/guards/auth.guard";
import { PermissionGuard } from "../../common/guards/permission.guard";
import { CurrentUser } from "../../common/decorators/current-user.decorator";
import { RequirePermission } from "../../common/decorators/require-permission.decorator";
import { CorrelationId } from "../../common/decorators/correlation-id.decorator";
import { RequireIdempotencyKey } from "../../common/decorators/require-idempotency-key.decorator";
import { AuditService } from "../audit/audit.module";

class CreateConversationDto { @IsString() @IsNotEmpty() @MaxLength(160) subject!: string; @IsString() @IsNotEmpty() @MaxLength(5000) message!: string; @IsOptional() @IsUUID() shipmentId?: string; }
class SendMessageDto { @IsString() @IsNotEmpty() @MaxLength(5000) body!: string; }
class UpdateConversationDto { @IsOptional() @IsIn(["OPEN", "WAITING_FOR_CUSTOMER", "WAITING_FOR_AGENT", "RESOLVED", "CLOSED"]) status?: string; @IsOptional() @IsUUID() assignedStaffUserId?: string; }

@Injectable()
class SupportConversationsService {
  constructor(private readonly audit: AuditService) {}
  listCustomer(userId: string) { return getPrismaClient().supportConversation.findMany({ where: { customerUserId: userId }, include: { shipment: { select: { trackingNumber: true } }, messages: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { lastMessageAt: "desc" } }); }
  listAdmin(status?: string) { const allowed = new Set(["OPEN", "WAITING_FOR_CUSTOMER", "WAITING_FOR_AGENT", "RESOLVED", "CLOSED"]); if (status && !allowed.has(status)) throw new BadRequestException("Unsupported conversation status"); return getPrismaClient().supportConversation.findMany({ where: status ? { status: status as never } : {}, include: { customerUser: { select: { fullName: true, email: true } }, shipment: { select: { trackingNumber: true } }, assignedStaffUser: { select: { fullName: true } } }, orderBy: { lastMessageAt: "desc" }, take: 100 }); }
  async create(userId: string, dto: CreateConversationDto, correlationId: string) { const subject = dto.subject.trim(); const message = dto.message.trim(); if (!subject || !message) throw new BadRequestException("Subject and message cannot be blank"); const prisma = getPrismaClient(); if (dto.shipmentId && !(await prisma.shipment.findFirst({ where: { id: dto.shipmentId, ownerUserId: userId }, select: { id: true } }))) throw new NotFoundException("Shipment not found"); return prisma.$transaction(async (tx) => { const item = await tx.supportConversation.create({ data: { customerUserId: userId, shipmentId: dto.shipmentId, subject, messages: { create: { authorType: "CUSTOMER", authorUserId: userId, body: message } } }, include: { messages: true } }); await this.audit.record({ actorUserId: userId, action: "SUPPORT_CONVERSATION_CREATED", entityType: "SupportConversation", entityId: item.id, correlationId }, tx); return item; }); }
  async messages(id: string, user: AuthenticatedUser, staff: boolean) { const item = await getPrismaClient().supportConversation.findUnique({ where: { id }, include: { messages: { include: { authorUser: { select: { fullName: true } } }, orderBy: { createdAt: "asc" } } } }); if (!item || (!staff && item.customerUserId !== user.userId)) throw new NotFoundException("Conversation not found"); return item; }
  async send(id: string, user: AuthenticatedUser, dto: SendMessageDto, staff: boolean, correlationId: string) { const body = dto.body.trim(); if (!body) throw new BadRequestException("Message cannot be blank"); const existing = await this.messages(id, user, staff); if (existing.status === "CLOSED") throw new BadRequestException("This conversation is closed"); const prisma = getPrismaClient(); return prisma.$transaction(async (tx) => { const message = await tx.supportMessage.create({ data: { conversationId: id, authorType: staff ? "STAFF" : "CUSTOMER", authorUserId: user.userId, body } }); await tx.supportConversation.update({ where: { id }, data: { lastMessageAt: new Date(), status: staff ? "WAITING_FOR_CUSTOMER" : "WAITING_FOR_AGENT", ...(staff && !existing.assignedStaffUserId ? { assignedStaffUserId: user.userId } : {}) } }); await this.audit.record({ actorUserId: user.userId, action: "SUPPORT_MESSAGE_SENT", entityType: "SupportConversation", entityId: id, correlationId }, tx); return message; }); }
  async update(id: string, dto: UpdateConversationDto, actorUserId: string, correlationId: string) { if (!dto.status && !dto.assignedStaffUserId) throw new BadRequestException("Provide a status or assignee"); const prisma = getPrismaClient(); if (dto.assignedStaffUserId) { const assignee = await prisma.user.findFirst({ where: { id: dto.assignedStaffUserId, staffRole: { not: null }, status: "ACTIVE" }, select: { id: true } }); if (!assignee) throw new BadRequestException("Assignee must be an active staff user"); } return prisma.$transaction(async (tx) => { const updated = await tx.supportConversation.update({ where: { id }, data: { ...(dto.status ? { status: dto.status as never } : {}), ...(dto.assignedStaffUserId ? { assignedStaffUserId: dto.assignedStaffUserId } : {}) } }); await this.audit.record({ actorUserId, action: "SUPPORT_CONVERSATION_UPDATED", entityType: "SupportConversation", entityId: id, correlationId }, tx); return updated; }); }
}

@UseGuards(AuthGuard) @Controller("me/support/conversations")
class CustomerSupportConversationsController { constructor(private readonly service: SupportConversationsService) {} @Get() list(@CurrentUser() u: AuthenticatedUser) { return this.service.listCustomer(u.userId); } @Post() @RequireIdempotencyKey() create(@Body() d: CreateConversationDto, @CurrentUser() u: AuthenticatedUser, @CorrelationId() c: string) { return this.service.create(u.userId, d, c); } @Get(":id/messages") messages(@Param("id", ParseUUIDPipe) id: string, @CurrentUser() u: AuthenticatedUser) { return this.service.messages(id, u, false); } @Post(":id/messages") @RequireIdempotencyKey() send(@Param("id", ParseUUIDPipe) id: string, @Body() d: SendMessageDto, @CurrentUser() u: AuthenticatedUser, @CorrelationId() c: string) { return this.service.send(id, u, d, false, c); } }

@UseGuards(AuthGuard, PermissionGuard) @RequirePermission("support:manage") @Controller("admin/support/conversations")
class AdminSupportConversationsController { constructor(private readonly service: SupportConversationsService) {} @Get() list(@Query("status") s?: string) { return this.service.listAdmin(s); } @Get(":id/messages") messages(@Param("id", ParseUUIDPipe) id: string, @CurrentUser() u: AuthenticatedUser) { return this.service.messages(id, u, true); } @Post(":id/messages") @RequireIdempotencyKey() send(@Param("id", ParseUUIDPipe) id: string, @Body() d: SendMessageDto, @CurrentUser() u: AuthenticatedUser, @CorrelationId() c: string) { return this.service.send(id, u, d, true, c); } @Patch(":id") @RequireIdempotencyKey() update(@Param("id", ParseUUIDPipe) id: string, @Body() d: UpdateConversationDto, @CurrentUser() u: AuthenticatedUser, @CorrelationId() c: string) { return this.service.update(id, d, u.userId, c); } }

@Module({ controllers: [CustomerSupportConversationsController, AdminSupportConversationsController], providers: [SupportConversationsService] })
export class SupportConversationsModule {}
